name: robogym
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pybullet
  - swig
  - cmake
  - pip
  - pip:
    - stable-baselines3==2.7.0
    - gymnasium==1.0.0
    - shimmy[gym-v26]==2.0.0
    - torch==2.5.1
    - torchvision==0.20.1
    - gymnasium[box2d]==1.0.0
    - pygame==2.6.1
    - pybullet-envs-gymnasium
    - git+https://github.com/benelot/pybullet-gym.git
    - optuna==4.1.0
    - tensorboard==2.18.0
    - matplotlib==3.9.3
    - pyyaml==6.0.2
    - numpy==1.26.4
    - pandas==2.2.3
    - tqdm==4.67.1
    - opencv-python==4.10.0.84
    - pillow==11.0.0
