environment:
  env_id: Walker2DBulletEnv-v0
demo:
  max_steps: 2000
training:
  target_score: 2500
  max_timesteps: 2000000
  learning_rate: 0.00020499985883250046
  policy_net:
  - 400
  - 300
  eval_freq: 10000
  n_steps: 2048
  batch_size: 128
  n_epochs: 10
  gamma: 0.995
  gae_lambda: 0.9
  clip_range: 0.1
  ent_coef: 0.009862653046214554
